name: Trigger monthly deployment
on:
  schedule:
    - cron: "0 0 1 * *"
permissions:
  contents: write
jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Deployment
        run: contents="$(jq ".description = \"$(date)\"" package.json)" && echo -E "${contents}" > package.json

      - name: Commit result
        run: |
          git config --global user.name 'Ryan Seipp'
          git config --global user.email 'rseipp@ryanseipp.com'
          git commit -am "Trigger monthly deployment"
          git push
